import mongoose from "mongoose";

const templateAttributesSchema = new mongoose.Schema({
  clinicId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Clinic",
    required: true,
  },
  doctorId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Doctor",
    required: true,
  },
  showMobileNumber: { type: Boolean, default: false },
  showPatientAddress: { type: Boolean, default: false },
  showTime: { type: Boolean, default: false },
  showAnthropometry: { type: Boolean, default: false },
  showDiagnosis: { type: Boolean, default: false },
  showComplaints: { type: Boolean, default: false },
  showFindings: { type: Boolean, default: false },
  showClinicalNotes: { type: Boolean, default: false },
  showDrugs: { type: Boolean, default: false },
  showSpecialDrugInstructions: { type: Boolean, default: false },
  showTests: { type: Boolean, default: false },
  showInstructions: { type: Boolean, default: false },
  showProcedures: { type: Boolean, default: false },
  showHandout: { type: Boolean, default: false },
  showFollowup: { type: Boolean, default: false },
  showSignature: { type: Boolean, default: false },
  showDoctorDetails: { type: Boolean, default: false },
  printPatientMilestone: { type: Boolean, default: false },
  printGrowthChart: { type: Boolean, default: false },
  printQRCode: { type: Boolean, default: false },
  showHistory: { type: Boolean, default: false },
  showLastVisit: { type: Boolean, default: false },
  showGenericNameFirst: { type: Boolean, default: false },
  showGenericName: { type: Boolean, default: false },
  showOnlyGenericName: { type: Boolean, default: false },
  showRegionalTranslations: { type: Boolean, default: false },
  prescribeOralDropsInMl: { type: Boolean, default: false },
  showDrugVolumeInTablet: { type: Boolean, default: false },
  showClinicNameInsteadOfDoctor: { type: Boolean, default: false },
  sharePrescriptionWithPatients: { type: Boolean, default: true },
  showDrugVolume: { type: Boolean, default: true },
  showReferences: { type: Boolean, default: true },
  applyOnlyDrugsWhenApplyPastPrescription: { type: Boolean, default: true },
});

export default mongoose.model("TemplateAttributes", templateAttributesSchema);
